// RECS — Bali Venue Data
// Source: Google Maps Takeout Export
// Last updated: 2026-02-19
//
// Each venue object:
//   id: unique identifier
//   name: venue name
//   description: 1-2 sentence description
//   cuisine: cuisine or venue type
//   category: restaurant | bar | cafe | beach_club | activity | wellness | stay
//   price: "$" | "$$" | "$$$"
//   rating: Google rating (number) or null
//   area: neighbourhood (Uluwatu, Canggu, Pererenan, Seminyak, Ubud, Sayan, etc.)
//   region: broader area (uluwatu, canggu, ubud)
//   userNote: personal note from Google Maps export or null
//   mapsUrl: original Google Maps URL from export
//   emoji: category emoji
//   tags: array of vibe/attribute tags

const RECS_VENUES = [

  // ═══════════════════════════════════════
  //  ULUWATU (31 venues)
  // ═══════════════════════════════════════

  {
    id: "ulu-001",
    name: "AVLI Modern Greek",
    description: "Contemporary Greek restaurant perched on the Uluwatu cliffs, serving elevated Mediterranean dishes with panoramic Indian Ocean views. Known for fresh seafood, grilled octopus, and an excellent wine list.",
    cuisine: "Greek / Mediterranean",
    category: "restaurant",
    price: "$$$",
    rating: 4.5,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/AVLI+modern+greek/data=!4m2!3m1!1s0x2dd2451a18a503d3:0x13affe71f7a2fe91",
    emoji: "🇬🇷",
    tags: ["Date night", "Views", "Splurge"],
    lat: -8.816562,
    lng: 115.095812,
    instagram: "avlibali"
  },
  {
    id: "ulu-002",
    name: "Ulu Fishmarket",
    description: "Fresh seafood market-style restaurant where you pick your catch and choose how it's cooked. Casual, bustling atmosphere right near the Uluwatu surf breaks.",
    cuisine: "Seafood",
    category: "restaurant",
    price: "$$",
    rating: 4.3,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Ulu+Fishmarket/data=!4m2!3m1!1s0x2dd245b35d2c0241:0x689baffca14f95e2",
    emoji: "🐟",
    tags: ["Casual", "Fresh", "Groups"],
    lat: -8.816709,
    lng: 115.095661
  },
  {
    id: "ulu-003",
    name: "YUKI Uluwatu",
    description: "Japanese-inspired restaurant in Uluwatu serving sushi, ramen, and izakaya-style small plates. Sleek modern interior with a good sake selection.",
    cuisine: "Japanese",
    category: "restaurant",
    price: "$$",
    rating: 4.4,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/YUKI+Uluwatu/data=!4m2!3m1!1s0x2dd24fcc0cc2fc6b:0xffa04618998f3f91",
    emoji: "🍣",
    tags: ["Date night", "Modern"],
    lat: -8.817091,
    lng: 115.093978,
    instagram: "yuki.uluwatu"
  },
  {
    id: "ulu-004",
    name: "ZALI Uluwatu",
    description: "Mediterranean-leaning all-day dining spot in the Bukit peninsula. Light, airy space with a focus on fresh ingredients and healthy options alongside indulgent mains.",
    cuisine: "Mediterranean",
    category: "restaurant",
    price: "$$",
    rating: 4.3,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/ZALI+Uluwatu/data=!4m2!3m1!1s0x2dd24fd77acf9841:0x97cdb7dc75bd6666",
    emoji: "🥗",
    tags: ["Healthy", "Brunch"],
    lat: -8.816859,
    lng: 115.094145,
    instagram: "zali.uluwatu"
  },
  {
    id: "ulu-005",
    name: "KALA Uluwatu — Greek Inspired Grill",
    description: "Open-fire Greek grill restaurant with a laid-back Bukit vibe. Known for its charcoal-grilled meats, halloumi, and pita. Great sunset spot.",
    cuisine: "Greek / Grill",
    category: "restaurant",
    price: "$$",
    rating: 4.5,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/KALA+Uluwatu+-+Greek+Inspired+Grill/data=!4m2!3m1!1s0x2dd245f0e8628d1b:0xa76cab4ad5ce54f1",
    emoji: "🔥",
    tags: ["Sunset", "Casual", "Groups"],
    lat: -8.812687,
    lng: 115.106831,
    instagram: "kalauluwatu"
  },
  {
    id: "ulu-006",
    name: "Lola's Cantina Mexicana — Uluwatu",
    description: "Colourful, buzzy Mexican joint with generous portions of tacos, burritos, and margaritas. One of the few late-night options in Uluwatu. Always packed.",
    cuisine: "Mexican",
    category: "restaurant",
    price: "$",
    rating: 4.4,
    area: "Bingin",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Lola%C2%B4s+Cantina+Mexicana+-+Uluwatu/data=!4m2!3m1!1s0x2dd245e438a65c11:0xc68c88be64aa159e",
    emoji: "🌮",
    tags: ["Late night", "Budget", "Groups"],
    lat: -8.817338,
    lng: 115.098454,
    instagram: "lolascantina.bali"
  },
  {
    id: "ulu-007",
    name: "Mana Uluwatu Restaurant & Bar",
    description: "Clifftop pool club and restaurant with dramatic ocean views. The infinity pool overlooking the Indian Ocean is the main draw — more of a vibe spot than a food destination.",
    cuisine: "International",
    category: "beach_club",
    price: "$$$",
    rating: 4.1,
    area: "Pecatu",
    region: "uluwatu",
    userNote: "Food shit, pool great",
    mapsUrl: "https://www.google.com/maps/place/Mana+Uluwatu+Restaurant+%26+Bar/data=!4m2!3m1!1s0x2dd24fd1e8e55d29:0x950a7a4cd9ba85ab",
    emoji: "🏊",
    tags: ["Pool", "Views", "Overpriced food"],
    lat: -8.818717,
    lng: 115.088009,
    instagram: "manauluwatu"
  },
  {
    id: "ulu-008",
    name: "By The Cliff",
    description: "Cliffside restaurant and pool club with sweeping ocean panoramas. Beautiful setting for sundowners — come for the views, not the kitchen.",
    cuisine: "International",
    category: "beach_club",
    price: "$$$",
    rating: 4.0,
    area: "Ungasan",
    region: "uluwatu",
    userNote: "Food shit, views and pool great",
    mapsUrl: "https://www.google.com/maps/place/By+The+Cliff/data=!4m2!3m1!1s0x2dd24f6e06782271:0x775ab78095f3a461",
    emoji: "🌊",
    tags: ["Views", "Pool", "Sunset"],
    lat: -8.845929,
    lng: 115.148540,
    instagram: "bythecliff.bali"
  },
  {
    id: "ulu-009",
    name: "Satu Uluwatu",
    description: "No-fuss warung-style eatery popular with surfers and expats. Good honest Indonesian and Western food at prices that won't hurt. The go-to when you just need a solid meal.",
    cuisine: "Indonesian / Western",
    category: "restaurant",
    price: "$",
    rating: 4.5,
    area: "Pecatu",
    region: "uluwatu",
    userNote: "Cheap and easy",
    mapsUrl: "https://www.google.com/maps/place/Satu+Uluwatu/data=!4m2!3m1!1s0x2dd245cdb1d34ee9:0x56425d9e0c0c5301",
    emoji: "🍛",
    tags: ["Budget", "Casual", "Everyday"],
    lat: -8.816535,
    lng: 115.112511
  },
  {
    id: "ulu-010",
    name: "Abracadabra by Mu Bungalow",
    description: "Dramatic clifftop venue built into the rock face with jaw-dropping ocean views. The setting is the entire point — perched right on the edge with waves crashing below.",
    cuisine: "International",
    category: "bar",
    price: "$$",
    rating: 4.2,
    area: "Bingin",
    region: "uluwatu",
    userNote: "On the cliff - wouldn't eat there but nice view",
    mapsUrl: "https://www.google.com/maps/place/Abracadabra+by+Mu+Bunglaow/data=!4m2!3m1!1s0x2dd24545ad956c67:0x613e99599987931d",
    emoji: "🪄",
    tags: ["Views", "Drinks only", "Sunset"],
    lat: -8.807038,
    lng: 115.112188,
    instagram: "drifterbali"
  },
  {
    id: "ulu-011",
    name: "Teja Uluwatu",
    description: "Modern rooftop bar and restaurant in Pecatu with craft cocktails and a Mediterranean-inspired menu. Popular for sundowners with a young, stylish crowd.",
    cuisine: "Mediterranean / Cocktails",
    category: "bar",
    price: "$$",
    rating: 4.3,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Teja+Uluwatu/data=!4m2!3m1!1s0x2dd24f8b46e2e527:0x6b7771cec4bcd1c8",
    emoji: "🍸",
    tags: ["Sunset", "Cocktails", "Trendy"],
    lat: -8.816017,
    lng: 115.090698,
    instagram: "palapa_uluwatu"
  },
  {
    id: "ulu-012",
    name: "ATMOS — BodyLab",
    description: "High-end fitness and wellness facility in Uluwatu with state-of-the-art equipment, personal training, and recovery services. Popular with the expat fitness crowd.",
    cuisine: "Fitness / Wellness",
    category: "wellness",
    price: "$$",
    rating: 4.7,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/ATMOS+-+BodyLab/data=!4m2!3m1!1s0x2dd2450046cba10f:0x2e882cc8ab792a88",
    emoji: "💪",
    tags: ["Fitness", "Premium"],
    lat: -8.814058,
    lng: 115.123195
  },
  {
    id: "ulu-013",
    name: "Grün Resort Uluwatu",
    description: "Boutique eco-resort tucked into the Uluwatu hillside with minimalist villas, a pool, and an on-site restaurant. Quiet and removed from the busier Bukit spots.",
    cuisine: "International",
    category: "stay",
    price: "$$$",
    rating: 4.6,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Gr%C3%BCn+Resort+Uluwatu/data=!4m2!3m1!1s0x2dd25b04f0993e9d:0x187887cd3537d1b6",
    emoji: "🌿",
    tags: ["Eco", "Quiet", "Romantic"],
    lat: -8.825164,
    lng: 115.107777
  },
  {
    id: "ulu-014",
    name: "Bartolo Bali",
    description: "Italian-inspired trattoria in Bingin serving handmade pasta, wood-fired pizza, and natural wines. Cozy, candlelit atmosphere that feels transported from rural Italy.",
    cuisine: "Italian",
    category: "restaurant",
    price: "$$",
    rating: 4.6,
    area: "Bingin",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Bartolo+Bali+%7C+Uluwatu/data=!4m2!3m1!1s0x2dd24545a91db69b:0xc947bc6c9491b59",
    emoji: "🍝",
    tags: ["Date night", "Italian", "Cozy"],
    lat: -8.813652,
    lng: 115.109950,
    instagram: "bartolo.bali"
  },
  {
    id: "ulu-015",
    name: "Il Salotto Bali",
    description: "Upscale Italian restaurant and lounge with a refined menu of pasta, risotto, and grilled mains. Elegant setting with attentive service — one of the nicer dinner spots in the Bukit.",
    cuisine: "Italian",
    category: "restaurant",
    price: "$$$",
    rating: 4.5,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Il+Salotto+Bali/data=!4m2!3m1!1s0x2dd2455a694690f1:0x94a8997221333d3a",
    emoji: "🇮🇹",
    tags: ["Splurge", "Date night", "Elegant"],
    lat: -8.816352,
    lng: 115.096243,
    instagram: "dum.dum.bali"
  },
  {
    id: "ulu-016",
    name: "Tabu",
    description: "Trendy restaurant and bar with a moody, design-forward interior. International menu with Asian influences, craft cocktails, and DJ sets on weekends.",
    cuisine: "International / Asian Fusion",
    category: "bar",
    price: "$$",
    rating: 4.3,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Tabu/data=!4m2!3m1!1s0x2dd245a42fade295:0x4183c26094c7af41",
    emoji: "🎵",
    tags: ["Nightlife", "Trendy", "Cocktails"],
    lat: -8.816490,
    lng: 115.095563
  },
  {
    id: "ulu-017",
    name: "Bonjour Uluwatu",
    description: "French-inspired café and bakery doing proper croissants, crêpes, and coffee. A welcome morning stop before hitting the surf or the beach clubs.",
    cuisine: "French / Bakery",
    category: "cafe",
    price: "$",
    rating: 4.4,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Bonjour+Uluwatu/data=!4m2!3m1!1s0x2dd25be1c29c02a1:0x2aefca6fdcc005ff",
    emoji: "🥐",
    tags: ["Breakfast", "Coffee", "Quick stop"],
    lat: -8.827666,
    lng: 115.139167,
    instagram: "cashewcanggu"
  },
  {
    id: "ulu-018",
    name: "Filini Restaurant",
    description: "Italian fine-casual restaurant at the Radisson Blu resort. Reliable pasta and pizza in a polished poolside setting. Not adventurous but consistently solid.",
    cuisine: "Italian",
    category: "restaurant",
    price: "$$",
    rating: 4.2,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Filini+Restaurant/data=!4m2!3m1!1s0x2dd245ef4555fb4b:0x794c70b352e9b68a",
    emoji: "🍕",
    tags: ["Hotel", "Reliable"],
    lat: -8.809001,
    lng: 115.110577
  },
  {
    id: "ulu-019",
    name: "OURS HOME",
    description: "Charming boutique villa and homestay in the Uluwatu area with a communal kitchen and relaxed communal vibe. Popular with digital nomads and longer-stay travellers.",
    cuisine: "Accommodation",
    category: "stay",
    price: "$",
    rating: 4.7,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/OURS+HOME/data=!4m2!3m1!1s0x2dd24f3d3386ca89:0xaef7b0a9c23cfed8",
    emoji: "🏠",
    tags: ["Budget", "Nomad", "Chill"],
    lat: -8.819493,
    lng: 115.089972,
    instagram: "singlefinbali"
  },
  {
    id: "ulu-020",
    name: "Ours Uluwatu",
    description: "Sister venue to OURS HOME — a café and co-working space with good coffee, smoothie bowls, and a relaxed atmosphere for working or hanging out.",
    cuisine: "Café / Health",
    category: "cafe",
    price: "$",
    rating: 4.5,
    area: "Bingin",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Ours+Uluwatu/data=!4m2!3m1!1s0x2dd2456046a221eb:0xa085b909ce850c46",
    emoji: "☕",
    tags: ["Working", "Coffee", "Chill"],
    lat: -8.819493,
    lng: 115.089972,
    instagram: "ondosbali"
  },
  {
    id: "ulu-021",
    name: "The Place With No Name",
    description: "Hidden gem bar and restaurant down a jungle path in Bingin. The kind of place you stumble upon and don't want to leave. Low-key, magical, fairy-lit.",
    cuisine: "International",
    category: "bar",
    price: "$$",
    rating: 4.6,
    area: "Bingin",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/The+Place+With+No+Name/data=!4m2!3m1!1s0x2dd245320d2f9c2f:0x3850a69e51102163",
    emoji: "✨",
    tags: ["Hidden gem", "Romantic", "Magical"],
    lat: -8.812374,
    lng: 115.106626,
    instagram: "savannabalangan"
  },
  {
    id: "ulu-022",
    name: "Rock Bar",
    description: "Iconic bar at the Ayana Resort, built into a natural rock formation 14 metres above the Indian Ocean. One of Bali's most famous sunset spots — arrive early, there's always a queue.",
    cuisine: "Cocktails / Light bites",
    category: "bar",
    price: "$$$",
    rating: 4.4,
    area: "Jimbaran",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Rock+Bar/data=!4m2!3m1!1s0x2dd24502e15014cd:0xea97e4a73abad2cf",
    emoji: "🪨",
    tags: ["Iconic", "Sunset", "Must-do"],
    lat: -8.784239,
    lng: 115.138471,
    instagram: "rockbarbali"
  },
  {
    id: "ulu-023",
    name: "Chela",
    description: "Mexican-inspired bar and taqueria with a surfy, casual vibe. Craft margaritas, mezcal cocktails, and solid street-food-style tacos. Good late-night option.",
    cuisine: "Mexican / Bar",
    category: "bar",
    price: "$",
    rating: 4.4,
    area: "Bingin",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/chela/data=!4m2!3m1!1s0x2dd2450f3ea3c4a5:0xd760bb15c083cd72",
    emoji: "🍹",
    tags: ["Late night", "Casual", "Cocktails"],
    lat: -8.812050,
    lng: 115.113325,
    instagram: "sundays.beach"
  },
  {
    id: "ulu-024",
    name: "Son of A Baker — Art & Bakehouse",
    description: "Artisan bakery and café doing sourdough, pastries, and specialty coffee. The kind of place where everything is made from scratch and you can taste it.",
    cuisine: "Bakery / Café",
    category: "cafe",
    price: "$",
    rating: 4.6,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Son+of+A+Baker-+Art+%26+Bakehouse/data=!4m2!3m1!1s0x2dd24596c7b672c5:0xf52f025149db089c",
    emoji: "🍞",
    tags: ["Breakfast", "Coffee", "Artisan"],
    lat: -8.812299,
    lng: 115.102834,
    instagram: "kliffbali"
  },
  {
    id: "ulu-025",
    name: "Bukit Sausage",
    description: "No-frills sausage and burger spot that's become a local legend. Handmade sausages, cold beers, and zero pretension. Exactly what you need after a surf session.",
    cuisine: "Burgers / Sausages",
    category: "restaurant",
    price: "$",
    rating: 4.5,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Bukit+Sausage/data=!4m2!3m1!1s0x2dd25bbf62543105:0xaa93d2793edde571",
    emoji: "🌭",
    tags: ["Budget", "Post-surf", "Casual"],
    lat: -8.827662,
    lng: 115.139106
  },
  {
    id: "ulu-026",
    name: "La Baracca Bali",
    description: "Italian osteria with a rustic, homely feel. Wood-fired pizza, fresh pasta, and a solid Italian wine selection. Consistently good — a local favourite for Italian food in the Bukit.",
    cuisine: "Italian",
    category: "restaurant",
    price: "$$",
    rating: 4.5,
    area: "Bingin",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/La+Baracca+Bali+(Uluwatu)/data=!4m2!3m1!1s0x2dd24555c40a5b37:0x4a2aa00904e3aa23",
    emoji: "🍕",
    tags: ["Italian", "Local fave", "Reliable"],
    lat: -8.816373,
    lng: 115.096168,
    instagram: "theungasan"
  },
  {
    id: "ulu-027",
    name: "BB52 Burgers — Uluwatu",
    description: "Smash burger joint doing juicy, no-nonsense burgers with proper buns and good fries. Nothing fancy, just really well-executed comfort food.",
    cuisine: "Burgers",
    category: "restaurant",
    price: "$",
    rating: 4.4,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/BB52+Burgers+-+Uluwatu/data=!4m2!3m1!1s0x2dd245b6d517044b:0x67426a413ea55bfb",
    emoji: "🍔",
    tags: ["Budget", "Comfort food", "Quick"],
    lat: -8.816597,
    lng: 115.097493,
    instagram: "sulubancliff"
  },
  {
    id: "ulu-028",
    name: "MASON. Uluwatu",
    description: "Upscale bar and grill with a dark, moody interior and excellent cocktail program. Known for their dry-aged steaks and late-night DJ sets. The Uluwatu sibling of M. MASON Canggu.",
    cuisine: "Grill / Cocktails",
    category: "bar",
    price: "$$$",
    rating: 4.4,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/MASON.+Uluwatu/data=!4m2!3m1!1s0x2dd245daf10c6d73:0xd265826351b4c7f2",
    emoji: "🥃",
    tags: ["Nightlife", "Steaks", "Cocktails"],
    lat: -8.816510,
    lng: 115.092575
  },
  {
    id: "ulu-029",
    name: "Ulu Garden",
    description: "Garden café and restaurant in a lush tropical setting. Mediterranean and Indonesian dishes, smoothie bowls, and a peaceful atmosphere away from the crowds.",
    cuisine: "Mediterranean / Indonesian",
    category: "restaurant",
    price: "$$",
    rating: 4.4,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Ulu+Garden/data=!4m2!3m1!1s0x2dd24fff5c7222b7:0x43a1b16e2fc72152",
    emoji: "🌺",
    tags: ["Garden", "Peaceful", "Healthy"],
    lat: -8.816602,
    lng: 115.093347
  },
  {
    id: "ulu-030",
    name: "The Loft",
    description: "Trendy multi-level restaurant and lounge with an industrial-chic aesthetic. International menu with Asian touches, good cocktails, and a rooftop terrace.",
    cuisine: "International",
    category: "restaurant",
    price: "$$",
    rating: 4.3,
    area: "Bingin",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/The+Loft/data=!4m2!3m1!1s0x2dd245561a6d75cb:0x2f56085763c4790d",
    emoji: "🏗️",
    tags: ["Trendy", "Rooftop", "Groups"],
    lat: -8.814390,
    lng: 115.112403
  },
  {
    id: "ulu-031",
    name: "NOURISH CAFE ULUWATU",
    description: "Health-focused café serving smoothie bowls, salads, juices, and plant-based meals. Clean, bright space popular with the yoga and wellness crowd.",
    cuisine: "Health food / Vegan",
    category: "cafe",
    price: "$",
    rating: 4.5,
    area: "Pecatu",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/NOURISH+CAFE+ULUWATU/data=!4m2!3m1!1s0x2dd245178e601297:0xac1573639130b803",
    emoji: "🥬",
    tags: ["Healthy", "Vegan", "Breakfast"],
    lat: -8.814567,
    lng: 115.112322
  },

  // ═══════════════════════════════════════
  //  CANGGU & PERERENAN (38 venues)
  // ═══════════════════════════════════════

  {
    id: "cgu-001",
    name: "Secana Rooftop Lounge",
    description: "Sleek rooftop bar in Seminyak with panoramic views, craft cocktails, and a resident DJ. Great for sundowners with a sophisticated crowd.",
    cuisine: "Cocktails / Light bites",
    category: "bar",
    price: "$$$",
    rating: 4.4,
    area: "Seminyak",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Secana+Rooftop+Lounge/data=!4m2!3m1!1s0x2dd2476f994aac09:0xcb5dac9dc8bc2135",
    emoji: "🌇",
    tags: ["Sunset", "Cocktails", "Trendy"],
    lat: -8.661547,
    lng: 115.135986,
    instagram: "theblackpigbali"
  },
  {
    id: "cgu-002",
    name: "Segno",
    description: "Italian wine bar and restaurant in Pererenan with a carefully curated wine list and handmade pasta. Intimate, candlelit space that feels like a secret.",
    cuisine: "Italian / Wine bar",
    category: "restaurant",
    price: "$$",
    rating: 4.6,
    area: "Pererenan",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Segno/data=!4m2!3m1!1s0x2dd2397072baa80b:0x8e9ca8e933afbfbf",
    emoji: "🍷",
    tags: ["Wine", "Date night", "Italian"],
    lat: -8.654950,
    lng: 115.131624,
    instagram: "fishtrapbali"
  },
  {
    id: "cgu-003",
    name: "Riviera Trattoria | Pererenan",
    description: "French-Italian trattoria with a charming garden setting. Fresh pasta, Provençal-inspired dishes, and a good natural wine list. Feels like the south of France somehow landed in Bali.",
    cuisine: "French-Italian",
    category: "restaurant",
    price: "$$",
    rating: 4.5,
    area: "Pererenan",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Riviera+Trattoria+%7C+Pererenan/data=!4m2!3m1!1s0x2dd2399c34a9b849:0xc6fd42c0e493fc6c",
    emoji: "🇫🇷",
    tags: ["Romantic", "Garden", "Wine"],
    lat: -8.647654,
    lng: 115.124424,
    instagram: "lunartacos"
  },
  {
    id: "cgu-004",
    name: "Bokashi Pererenan",
    description: "Plant-forward restaurant and deli focused on fermented foods, organic produce, and sustainable dining. Innovative menu that takes healthy eating seriously without being boring.",
    cuisine: "Health / Organic",
    category: "restaurant",
    price: "$$",
    rating: 4.5,
    area: "Pererenan",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Bokashi+Pererenan/data=!4m2!3m1!1s0x2dd2390032e2ed57:0x5382b3c4ffc2a897",
    emoji: "🌱",
    tags: ["Healthy", "Organic", "Innovative"],
    lat: -8.650551,
    lng: 115.122282,
    instagram: "naluboweats"
  },
  {
    id: "cgu-005",
    name: "Jade by Todd English",
    description: "Celebrity chef Todd English's Bali outpost serving Pan-Asian cuisine in a stunning setting. Dim sum, sushi, and wok dishes in a glamorous space — special occasion territory.",
    cuisine: "Pan-Asian",
    category: "restaurant",
    price: "$$$",
    rating: 4.3,
    area: "Seminyak",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Jade+by+Todd+English/data=!4m2!3m1!1s0x2dd24703d2edb92d:0x7a48f3270487f525",
    emoji: "🐉",
    tags: ["Splurge", "Special occasion", "Pan-Asian"],
    lat: -8.659373,
    lng: 115.138283,
    instagram: "kintamanicoffee"
  },
  {
    id: "cgu-006",
    name: "Red Gunpowder",
    description: "Bold Indian restaurant with a modern twist on classic dishes. Rich curries, tandoori, and creative cocktails in a vibrant, atmospheric setting.",
    cuisine: "Indian",
    category: "restaurant",
    price: "$$",
    rating: 4.4,
    area: "Pererenan",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Red+Gunpowder/data=!4m2!3m1!1s0x2dd239e4946ee7e7:0x60cf923d94156552",
    emoji: "🌶️",
    tags: ["Spicy", "Flavourful", "Date night"],
    lat: -8.646305,
    lng: 115.127713
  },
  {
    id: "cgu-007",
    name: "L'Avenue Cafe Restaurant",
    description: "French-style café in Seminyak with all-day brunch, patisserie, and European-inspired mains. Popular for its eggs Benedict and elegant garden terrace.",
    cuisine: "French / Café",
    category: "cafe",
    price: "$$",
    rating: 4.3,
    area: "Seminyak",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/L'Avenue+Cafe+Restaurant/data=!4m2!3m1!1s0x2dd247c181166c09:0xde3e7c4fcd7dd282",
    emoji: "🥐",
    tags: ["Brunch", "French", "Garden"],
    lat: -8.656578,
    lng: 115.140985,
    instagram: "littleflinders_"
  },
  {
    id: "cgu-008",
    name: "Vagabondo",
    description: "Italian restaurant in Seminyak known for excellent thin-crust pizza and homemade pasta. Casual, friendly atmosphere with a loyal following among locals and expats.",
    cuisine: "Italian",
    category: "restaurant",
    price: "$$",
    rating: 4.4,
    area: "Seminyak",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Vagabondo/data=!4m2!3m1!1s0x2dd247d8a4bf59dd:0x485dd7857e55e5f",
    emoji: "🍝",
    tags: ["Italian", "Casual", "Local fave"],
    lat: -8.671676,
    lng: 115.162490,
    instagram: "pinchbali"
  },
  {
    id: "cgu-009",
    name: "ZAI Cafe",
    description: "Modern café with a Southeast Asian twist. Good coffee, creative brunch menu, and a photogenic interior. Popular with the remote-work crowd.",
    cuisine: "Café / Asian-fusion",
    category: "cafe",
    price: "$",
    rating: 4.3,
    area: "Seminyak",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/ZAI+cafe/data=!4m2!3m1!1s0x2dd247a5b7db3d9d:0xbff2a1a1fcdf0b52",
    emoji: "☕",
    tags: ["Coffee", "Working", "Brunch"],
    lat: -8.645101,
    lng: 115.141394,
    instagram: "ishibali"
  },
  {
    id: "cgu-010",
    name: "LILA BROWN",
    description: "Specialty coffee shop and brunch spot in Seminyak. Third-wave coffee, smoothie bowls, and a clean minimalist aesthetic. The oat flat white is excellent.",
    cuisine: "Coffee / Brunch",
    category: "cafe",
    price: "$",
    rating: 4.5,
    area: "Seminyak",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/LILA+BROWN/data=!4m2!3m1!1s0x2dd247d7e52a72a1:0x82ffaf60e9e467f8",
    emoji: "☕",
    tags: ["Coffee", "Brunch", "Aesthetic"],
    lat: -8.659588,
    lng: 115.139864,
    instagram: "themiddlebali"
  },
  {
    id: "cgu-011",
    name: "Santana Brasserie Latina",
    description: "Latin-inspired brasserie with a lively atmosphere. South American dishes, ceviches, and cocktails with a tropical twist. Gets buzzy at night with live music.",
    cuisine: "Latin American",
    category: "restaurant",
    price: "$$",
    rating: 4.3,
    area: "Seminyak",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Santana+Brasserie+Latina/data=!4m2!3m1!1s0x2dd2479aef9cb78d:0x77215eb9d10e00ef",
    emoji: "💃",
    tags: ["Lively", "Latin", "Groups"],
    lat: -8.659677,
    lng: 115.139259
  },
  {
    id: "cgu-012",
    name: "Bar Vera Bistro & Wine Bar",
    description: "Intimate wine bar and bistro in Pererenan with an exceptional natural wine list and tapas-style sharing plates. Feels like a wine bar you'd find in a European capital.",
    cuisine: "Wine bar / Tapas",
    category: "bar",
    price: "$$",
    rating: 4.6,
    area: "Pererenan",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Bar+Vera+Bistro+%26+Wine+Bar/data=!4m2!3m1!1s0x2dd2396ace6f70a3:0x65667fc87218a51b",
    emoji: "🍷",
    tags: ["Wine", "Date night", "Intimate"],
    lat: -8.642963,
    lng: 115.129107,
    instagram: "warunglocal"
  },
  {
    id: "cgu-013",
    name: "Shelter Restaurant",
    description: "Modern Australian-inspired restaurant on Batu Bolong. Elevated brunch and dinner with creative cocktails. The interiors are gorgeous — concrete, timber, and tropical plants.",
    cuisine: "Australian / International",
    category: "restaurant",
    price: "$$",
    rating: 4.3,
    area: "Canggu",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Shelter+Restaurant/data=!4m2!3m1!1s0x2dd2398f2648fc71:0x1b781077a2debbb2",
    emoji: "🌿",
    tags: ["Brunch", "Design", "Cocktails"],
    lat: -8.648103,
    lng: 115.124339,
    instagram: "creamybali"
  },
  {
    id: "cgu-014",
    name: "WOODS Pererenan",
    description: "Plant-filled café and restaurant with a farm-to-table philosophy. Seasonal menus, specialty coffee, and a beautiful garden space. One of Pererenan's best brunch spots.",
    cuisine: "Farm-to-table / Café",
    category: "restaurant",
    price: "$$",
    rating: 4.5,
    area: "Pererenan",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/WOODS+PERERENAN/data=!4m2!3m1!1s0x2dd23932c81a38b5:0xcf6a7e485aa66562",
    emoji: "🌳",
    tags: ["Brunch", "Garden", "Organic"],
    lat: -8.645919,
    lng: 115.128236,
    instagram: "pomodorobali"
  },
  {
    id: "cgu-015",
    name: "Lulu Bistrot Bali",
    description: "Charming French bistrot in Pererenan with a short, considered menu. Classic dishes done really well — steak frites, duck confit, crème brûlée. Unpretentious and delicious.",
    cuisine: "French",
    category: "restaurant",
    price: "$$",
    rating: 4.6,
    area: "Pererenan",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Lulu+Bistrot+Bali/data=!4m2!3m1!1s0x2dd23960a9483fc3:0xe9ae745a9d6f8c3e",
    emoji: "🇫🇷",
    tags: ["French", "Cozy", "Date night"],
    lat: -8.653234,
    lng: 115.132599,
    instagram: "streatcoffee"
  },
  {
    id: "cgu-016",
    name: "Banyoo",
    description: "Open-air restaurant set among bamboo structures with a focus on clean, healthy food. Smoothie bowls, salads, and light Indonesian dishes in a zen garden setting.",
    cuisine: "Health / Indonesian",
    category: "restaurant",
    price: "$",
    rating: 4.3,
    area: "Canggu",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Banyoo/data=!4m2!3m1!1s0x2dd2459012f5eeab:0xf9eb4d960b71f3b9",
    emoji: "🎋",
    tags: ["Healthy", "Peaceful", "Garden"],
    lat: -8.811437,
    lng: 115.131851,
    instagram: "nuddle.bali"
  },
  {
    id: "cgu-017",
    name: "ARTE Canggu",
    description: "Gallery, restaurant, and creative space rolled into one. International menu in a striking architectural setting with rotating art exhibitions. More than just a meal.",
    cuisine: "International",
    category: "restaurant",
    price: "$$",
    rating: 4.2,
    area: "Canggu",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/ARTE+Canggu/data=!4m2!3m1!1s0x2dd239157fa29935:0x8962f6278125f1cb",
    emoji: "🎨",
    tags: ["Art", "Design", "Unique"],
    lat: -8.650502,
    lng: 115.122019,
    instagram: "shakeahand.bali"
  },
  {
    id: "cgu-018",
    name: "Sa'Mesa Canggu",
    description: "Sardinian-inspired restaurant with a communal dining philosophy. Handmade pasta, rustic Italian mains, and a warm convivial atmosphere. The name means 'the table' in Sardinian.",
    cuisine: "Italian / Sardinian",
    category: "restaurant",
    price: "$$",
    rating: 4.5,
    area: "Canggu",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Sa'Mesa+Canggu/data=!4m2!3m1!1s0x2dd239528ce07f01:0xcdf8175e4a1dad49",
    emoji: "🍝",
    tags: ["Italian", "Communal", "Cozy"],
    lat: -8.647634,
    lng: 115.136450
  },
  {
    id: "cgu-019",
    name: "Nirvana Life Fitness and Wellness Club",
    description: "Premium gym and wellness centre with a full range of equipment, classes, pool, and spa facilities. The nicest fitness option in the Canggu area.",
    cuisine: "Fitness / Wellness",
    category: "wellness",
    price: "$$",
    rating: 4.5,
    area: "Canggu",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Nirvana+Life+Fitness+and+Wellness+Club/data=!4m2!3m1!1s0x2dd238903e65b6f3:0xb6e49f677de888b8",
    emoji: "💪",
    tags: ["Fitness", "Pool", "Premium"],
    lat: -8.642638,
    lng: 115.154363,
    instagram: "thecanggumarket"
  },
  {
    id: "cgu-020",
    name: "Bali Padel Academy",
    description: "Padel tennis courts in Canggu — one of the first proper padel facilities in Bali. Book a court or join social sessions. Growing fast with the expat community.",
    cuisine: "Padel / Sport",
    category: "activity",
    price: "$",
    rating: 4.6,
    area: "Canggu",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Bali+Padel+Academy/data=!4m2!3m1!1s0x2dd239aff8521b05:0x666bf375098e25d7",
    emoji: "🎾",
    tags: ["Sport", "Social", "Active"],
    lat: -8.627760,
    lng: 115.148004,
    instagram: "milkandmadubali"
  },
  {
    id: "cgu-021",
    name: "Penny Lane",
    description: "Retro-themed bar and live music venue in Canggu. Classic cocktails, craft beers, and regular live bands. A proper pub with character — not another generic beach bar.",
    cuisine: "Bar / Live music",
    category: "bar",
    price: "$",
    rating: 4.4,
    area: "Canggu",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Penny+Lane/data=!4m2!3m1!1s0x2dd239280ce521ed:0x38561eb161bdcd68",
    emoji: "🎸",
    tags: ["Live music", "Casual", "Nightlife"],
    lat: -8.653356,
    lng: 115.130567,
    instagram: "cocobali"
  },
  {
    id: "cgu-022",
    name: "Black Sand Brewery",
    description: "Canggu's own craft brewery with a taproom pouring house-brewed beers. IPAs, lagers, stouts — all brewed on-site. Bar food and a chilled industrial vibe.",
    cuisine: "Craft beer / Bar food",
    category: "bar",
    price: "$",
    rating: 4.4,
    area: "Canggu",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Black+Sand+Brewery/data=!4m2!3m1!1s0x2dd2391220f23837:0x98de4df6776757a4",
    emoji: "🍺",
    tags: ["Craft beer", "Casual", "Groups"],
    lat: -8.645566,
    lng: 115.141264,
    instagram: "ji.restaurant"
  },
  {
    id: "cgu-023",
    name: "Wrong Gym",
    description: "Trendy, well-equipped gym in Canggu popular with fitness enthusiasts and digital nomads. Strength training focused with a cool industrial aesthetic.",
    cuisine: "Fitness",
    category: "wellness",
    price: "$",
    rating: 4.5,
    area: "Canggu",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Wrong+Gym/data=!4m2!3m1!1s0x2dd2390553852d1d:0xe5a369db94e2ee1d",
    emoji: "🏋️",
    tags: ["Fitness", "Nomad", "Cool"],
    lat: -8.651474,
    lng: 115.121347,
    instagram: "luiginiscanggu"
  },
  {
    id: "cgu-024",
    name: "M. MASON Bar | Grill Canggu",
    description: "Upscale grill restaurant and cocktail bar with an industrial-luxe interior. Dry-aged steaks, craft cocktails, and a moody late-night atmosphere. The original MASON venue.",
    cuisine: "Grill / Cocktails",
    category: "bar",
    price: "$$$",
    rating: 4.5,
    area: "Canggu",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/M.+MASON+Bar+%7C+Grill+Canggu/data=!4m2!3m1!1s0x2dd239105a5f6c05:0xd0f22ee258c2bdcd",
    emoji: "🥃",
    tags: ["Steaks", "Cocktails", "Nightlife"],
    lat: -8.653957,
    lng: 115.131792,
    instagram: "tacosbali"
  },
  {
    id: "cgu-025",
    name: "Lola's Cantina Mexicana — Canggu",
    description: "The Canggu outpost of the popular Mexican chain. Same formula — generous tacos, burritos, and frozen margaritas in a colourful, high-energy space.",
    cuisine: "Mexican",
    category: "restaurant",
    price: "$",
    rating: 4.3,
    area: "Canggu",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Lola%E2%80%99s+Cantina+Mexicana+-+Canggu/data=!4m2!3m1!1s0x2dd2390529900405:0x3634a6a0e550a21b",
    emoji: "🌮",
    tags: ["Mexican", "Budget", "Groups"],
    lat: -8.653447,
    lng: 115.136611,
    instagram: "vuelvecarolina.bali"
  },
  {
    id: "cgu-026",
    name: "Copenhagen Canggu",
    description: "Scandinavian-inspired café and restaurant with clean design and a Nordic-meets-tropical menu. Great coffee, smørrebrød-style dishes, and minimalist interiors.",
    cuisine: "Scandinavian / Café",
    category: "cafe",
    price: "$$",
    rating: 4.4,
    area: "Canggu",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Copenhagen+Canggu/data=!4m2!3m1!1s0x2dd2386340b679bd:0x260f391f0c4d2633",
    emoji: "🇩🇰",
    tags: ["Coffee", "Design", "Brunch"],
    lat: -8.646070,
    lng: 115.133800,
    instagram: "crumbsbali"
  },
  {
    id: "cgu-027",
    name: "The Shady Pig",
    description: "Barbecue and smokehouse with a laid-back, surfer-friendly vibe. Slow-smoked meats, craft beers, and live music. Messy, satisfying, and fun.",
    cuisine: "BBQ / Smokehouse",
    category: "restaurant",
    price: "$$",
    rating: 4.3,
    area: "Seminyak",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/The+Shady+Pig/data=!4m2!3m1!1s0x2dd247edaa7598c5:0xafcc752555d615e4",
    emoji: "🐷",
    tags: ["BBQ", "Casual", "Live music"],
    lat: -8.659566,
    lng: 115.139822,
    instagram: "wategardens"
  },
  {
    id: "cgu-028",
    name: "MORABITO ART VILLA",
    description: "Stunning art-filled luxury villa available for events and stays. Each room is curated with contemporary art. Not a restaurant — a destination in itself for design lovers.",
    cuisine: "Art / Accommodation",
    category: "stay",
    price: "$$$",
    rating: 4.7,
    area: "Seminyak",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/MORABITO+ART+VILLA/data=!4m2!3m1!1s0x2dd2479d75bf1d5f:0xeb6a2518cdaf165f",
    emoji: "🎨",
    tags: ["Art", "Luxury", "Design"],
    lat: -8.667408,
    lng: 115.140487,
    instagram: "heywrld"
  },
  {
    id: "cgu-029",
    name: "Mrs Sippy Bali",
    description: "Iconic pool club in Seminyak with a massive salt-water pool, diving boards, and all-day DJs. The classic Bali day-party venue — arrive early to get a sun lounger.",
    cuisine: "Pool club / Cocktails",
    category: "beach_club",
    price: "$$",
    rating: 4.2,
    area: "Seminyak",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Mrs+Sippy+Bali/data=!4m2!3m1!1s0x2dd2470dd8749eab:0x329f9432dee17526",
    emoji: "🏊",
    tags: ["Pool", "Party", "Groups"],
    lat: -8.679589,
    lng: 115.151247,
    instagram: "mrssippybali"
  },
  {
    id: "cgu-030",
    name: "Spring Spa Seminyak",
    description: "Highly-rated spa in Seminyak offering Balinese massage, facials, and body treatments. Clean, professional, and well-priced compared to hotel spas.",
    cuisine: "Spa",
    category: "wellness",
    price: "$$",
    rating: 4.7,
    area: "Seminyak",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Spring+Spa+Seminyak/data=!4m2!3m1!1s0x2dd247131b99639f:0x10ef8f21af50cc0f",
    emoji: "💆",
    tags: ["Spa", "Relaxation", "Treat"],
    lat: -8.683339,
    lng: 115.156449,
    instagram: "theoldmans"
  },
  {
    id: "cgu-031",
    name: "Body Factory Bali",
    description: "Full-service gym and fitness centre with a wide range of equipment and classes. One of Seminyak's go-to gyms for both short-term visitors and long-term expats.",
    cuisine: "Fitness",
    category: "wellness",
    price: "$",
    rating: 4.4,
    area: "Seminyak",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Body+Factory+Bali/data=!4m2!3m1!1s0x2dd24756803b6cdd:0x2c12b148b65fb",
    emoji: "🏋️",
    tags: ["Fitness", "Gym"],
    lat: -8.656011,
    lng: 115.134892,
    instagram: "sandbarbali"
  },
  {
    id: "cgu-032",
    name: "La Brisa Bali",
    description: "Bohemian beach club built from reclaimed fishing boats on Echo Beach. Stunning rustic design, pools, and legendary sunset views. One of Bali's most Instagrammed venues. Sunday market is a highlight.",
    cuisine: "Mediterranean / Seafood",
    category: "beach_club",
    price: "$$$",
    rating: 4.1,
    area: "Canggu",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/La+Brisa+Bali+%7C+Beach+Club/data=!4m2!3m1!1s0x2dd23876693af8ad:0x86929db7c4eabc29",
    emoji: "🚣",
    tags: ["Iconic", "Sunset", "Beach club"],
    lat: -8.654173,
    lng: 115.125809,
    instagram: "labrisabali"
  },
  {
    id: "cgu-033",
    name: "Motel Mexicola",
    description: "A Seminyak institution. Retro Mexican-themed bar and restaurant with neon signs, mariachi bands, and strong margaritas. Loud, colourful, and unapologetically fun.",
    cuisine: "Mexican / Bar",
    category: "bar",
    price: "$$",
    rating: 4.3,
    area: "Seminyak",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Motel+Mexicola/data=!4m2!3m1!1s0x2dd247102a7b7f25:0x7bc3bd199203e28b",
    emoji: "🎪",
    tags: ["Iconic", "Nightlife", "Fun"],
    lat: -8.682134,
    lng: 115.153795,
    instagram: "motelmexicola"
  },
  {
    id: "cgu-034",
    name: "The Shady Fox",
    description: "Cocktail bar and restaurant with a refined menu and expertly mixed drinks. Slightly more grown-up than the typical Canggu offering — think low lighting and conversation-level music.",
    cuisine: "Cocktails / International",
    category: "bar",
    price: "$$",
    rating: 4.4,
    area: "Canggu",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/The+Shady+Fox/data=!4m2!3m1!1s0x2dd239c10f78003b:0x32d6416e6e16679e",
    emoji: "🦊",
    tags: ["Cocktails", "Date night", "Chill"],
    lat: -8.646187,
    lng: 115.127813,
    instagram: "thebillboardbali"
  },
  {
    id: "cgu-035",
    name: "iam Vegan Babe",
    description: "Fully vegan restaurant and café in Canggu with creative plant-based dishes that even non-vegans love. Colourful bowls, burgers, and desserts. Fun, playful branding.",
    cuisine: "Vegan",
    category: "restaurant",
    price: "$",
    rating: 4.5,
    area: "Canggu",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/iam+Vegan+Babe/data=!4m2!3m1!1s0x2dd2391e8fef746d:0x45bbc987f00c4115",
    emoji: "🌱",
    tags: ["Vegan", "Fun", "Healthy"],
    lat: -8.651151,
    lng: 115.131788,
    instagram: "tamanbhagawan"
  },
  {
    id: "cgu-036",
    name: "FINNS Recreation Club",
    description: "Massive multi-venue complex with pools, a bowling alley, trampolines, gym, and multiple restaurants. The all-in-one day out in Canggu — especially good if you have kids.",
    cuisine: "Recreation / Multiple",
    category: "beach_club",
    price: "$$",
    rating: 4.2,
    area: "Canggu",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/FINNS+Recreation+Club/data=!4m2!3m1!1s0x2dd239942b306afb:0x35a92bd5189298d",
    emoji: "🎳",
    tags: ["Pool", "Groups", "All-day"],
    lat: -8.662469,
    lng: 115.147845,
    instagram: "atlasbeachfest"
  },
  {
    id: "cgu-037",
    name: "Potato Head Beach Club",
    description: "Design-forward beach club and cultural complex in Seminyak. The colosseum-like facade made from vintage shutters is iconic. Pools, restaurants, sunset DJs, and a sustainability-focused ethos. Kaum restaurant downstairs does serious Indonesian food.",
    cuisine: "International / Multiple",
    category: "beach_club",
    price: "$$$",
    rating: 4.3,
    area: "Seminyak",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Potato+Head+Beach+Club/data=!4m2!3m1!1s0x2dd24711ff4b76fd:0x1b9dac1a58048d4e",
    emoji: "🏛️",
    tags: ["Iconic", "Design", "Sunset"],
    lat: -8.679435,
    lng: 115.149934,
    instagram: "potatoheadbali"
  },
  {
    id: "cgu-038",
    name: "Sundays Beach Club",
    description: "Exclusive beach club accessible by inclinator down a cliff face. White sand cove, crystal-clear water, and a Robinson Crusoe vibe. One of Bali's most beautiful beach settings.",
    cuisine: "International / Seafood",
    category: "beach_club",
    price: "$$$",
    rating: 4.5,
    area: "Ungasan",
    region: "canggu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Sundays+Beach+Club/data=!4m2!3m1!1s0x2dd25b052ba7ef3f:0xb38f06acc4d67a83",
    emoji: "🏖️",
    tags: ["Beach", "Exclusive", "Beautiful"],
    lat: -8.847121,
    lng: 115.150740,
    instagram: "finnsbeachclub"
  },

  // ═══════════════════════════════════════
  //  UBUD & SAYAN (18 venues)
  // ═══════════════════════════════════════

  {
    id: "ubd-001",
    name: "Suwat Waterfall",
    description: "Dramatic waterfall tucked away from the tourist trail near Ubud. Less crowded than Tegenungan, with a powerful cascade and a natural swimming pool at the base. Worth the steep stairs down.",
    cuisine: "Natural attraction",
    category: "activity",
    price: "$",
    rating: 4.6,
    area: "Tampaksiring",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Suwat+Waterfall/data=!4m2!3m1!1s0x2dd217a1866f1383:0xe9ff0904a23da5fb",
    emoji: "🌊",
    tags: ["Nature", "Off-trail", "Swimming"],
    lat: -8.487664,
    lng: 115.317864
  },
  {
    id: "ubd-002",
    name: "Taman Sari Waterfall & Natural Pool",
    description: "Hidden waterfall with a beautiful natural pool surrounded by jungle. Quieter than the more famous falls — feels like your own private swimming spot in the rainforest.",
    cuisine: "Natural attraction",
    category: "activity",
    price: "$",
    rating: 4.5,
    area: "Gianyar",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Taman+Sari+Waterfall+%26+Natural+pool/data=!4m2!3m1!1s0x2dd217356ee10a41:0xba30329b382d3779",
    emoji: "🏊",
    tags: ["Nature", "Hidden gem", "Swimming"],
    lat: -8.502219,
    lng: 115.328322,
    instagram: "kafeinubud"
  },
  {
    id: "ubd-003",
    name: "Omma Dayclub Bali",
    description: "Luxury dayclub on the outskirts of Ubud with infinity pools, cabanas, and international DJs. A Mykonos-meets-jungle concept — surprisingly fun for the Ubud area.",
    cuisine: "Day club / Cocktails",
    category: "beach_club",
    price: "$$$",
    rating: 4.2,
    area: "Ubud",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Omma+Dayclub+Bali/data=!4m2!3m1!1s0x2dd2157de227d9e3:0x1c5c1d412294da8e",
    emoji: "🎶",
    tags: ["Pool", "Party", "Splurge"],
    lat: -8.575615,
    lng: 115.289497,
    instagram: "makanplacexubud"
  },
  {
    id: "ubd-004",
    name: "Donna",
    description: "Chic Italian restaurant in Ubud with a beautiful open-air setting. Handmade pasta, wood-fired dishes, and Italian wines. The ambience is elegant without being stuffy.",
    cuisine: "Italian",
    category: "restaurant",
    price: "$$",
    rating: 4.5,
    area: "Central Ubud",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Donna/data=!4m2!3m1!1s0x2dd23d6aa797bb8b:0x24b5d5d00ac99b53",
    emoji: "🍝",
    tags: ["Italian", "Elegant", "Date night"],
    lat: -8.513045,
    lng: 115.260718
  },
  {
    id: "ubd-005",
    name: "Brie Restaurant & Cheesery",
    description: "A cheese lover's paradise in Ubud. Raclette, fondue, cheese boards, and a menu built around artisanal cheese — many made in-house. Unique concept that somehow works brilliantly in Bali.",
    cuisine: "French / Cheese",
    category: "restaurant",
    price: "$$",
    rating: 4.6,
    area: "Central Ubud",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Brie+Restaurant+%26+Cheesery/data=!4m2!3m1!1s0x2dd23dd5265bc4a9:0x5abc4293e0ca5286",
    emoji: "🧀",
    tags: ["Unique", "Cheese", "Must-try"],
    lat: -8.506299,
    lng: 115.251821,
    instagram: "copperubud"
  },
  {
    id: "ubd-006",
    name: "Zest",
    description: "Fresh, plant-forward restaurant in Ubud with a focus on raw foods, juices, and creative vegan dishes. Airy, light-filled space that feels healthy just walking in.",
    cuisine: "Vegan / Raw",
    category: "restaurant",
    price: "$$",
    rating: 4.4,
    area: "Central Ubud",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Zest/data=!4m2!3m1!1s0x2dd23d3dfd1f975f:0xf6e33b9c72b33935",
    emoji: "🥬",
    tags: ["Vegan", "Healthy", "Clean"],
    lat: -8.504949,
    lng: 115.253735
  },
  {
    id: "ubd-007",
    name: "Merlin's",
    description: "Eclectic café and gallery space in Ubud with a bohemian vibe. Good coffee, light meals, and a creative atmosphere. The kind of place you settle into for a few hours.",
    cuisine: "Café / International",
    category: "cafe",
    price: "$",
    rating: 4.3,
    area: "Central Ubud",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Merlin's/data=!4m2!3m1!1s0x2dd23d2cd9fd3743:0x9b058ab00f1ab8bc",
    emoji: "🧙",
    tags: ["Bohemian", "Coffee", "Creative"],
    lat: -8.522237,
    lng: 115.262949,
    instagram: "daumpohbali"
  },
  {
    id: "ubd-008",
    name: "Room4Dessert",
    description: "Innovative dessert-focused tasting menu by acclaimed pastry chef Will Goldfarb. 10+ course dessert experience that's part art, part theatre, part sugar rush. Completely unique — there's nothing else like it in Bali.",
    cuisine: "Dessert / Fine dining",
    category: "restaurant",
    price: "$$$",
    rating: 4.7,
    area: "Central Ubud",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Room4Dessert/data=!4m2!3m1!1s0x2dd23d30e41cdf4d:0x5c9b53e04a5de852",
    emoji: "🍰",
    tags: ["Unique", "Must-do", "Fine dining"],
    lat: -8.492647,
    lng: 115.253266,
    instagram: "r4d_room4dessert"
  },
  {
    id: "ubd-009",
    name: "The Lair",
    description: "Atmospheric cocktail bar in Ubud with a dark, moody interior and expertly crafted drinks. One of the few proper cocktail bars in town — a welcome change from the juice-bar scene.",
    cuisine: "Cocktails",
    category: "bar",
    price: "$$",
    rating: 4.4,
    area: "Central Ubud",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/The+Lair/data=!4m2!3m1!1s0x2dd23d6620ca1569:0x212382b1bb25f885",
    emoji: "🍸",
    tags: ["Cocktails", "Moody", "Date night"],
    lat: -8.504993,
    lng: 115.254423
  },
  {
    id: "ubd-010",
    name: "Honey & Smoke",
    description: "Middle Eastern and Mediterranean grill restaurant with dishes cooked over open flame. Generous sharing plates, smoky flavours, and a warm, buzzy atmosphere.",
    cuisine: "Middle Eastern / Mediterranean",
    category: "restaurant",
    price: "$$",
    rating: 4.5,
    area: "Central Ubud",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Honey+%26+Smoke/data=!4m2!3m1!1s0x2dd23dcfc9d4eb09:0x99935286c7cc0179",
    emoji: "🔥",
    tags: ["Sharing", "Smoky", "Groups"],
    lat: -8.513201,
    lng: 115.260700
  },
  {
    id: "ubd-011",
    name: "Locavore To Go",
    description: "The casual offshoot of Ubud's legendary Locavore fine dining restaurant. Same philosophy of local, seasonal Indonesian ingredients but in burger, sandwich, and bowl form. Incredible value.",
    cuisine: "Indonesian / Modern",
    category: "cafe",
    price: "$",
    rating: 4.5,
    area: "Central Ubud",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Locavore+To+Go/data=!4m2!3m1!1s0x2dd23d6c76742a71:0x482b661125cad21a",
    emoji: "🍔",
    tags: ["Local fave", "Value", "Quick"],
    lat: -8.510373,
    lng: 115.264281
  },
  {
    id: "ubd-012",
    name: "Batubara Wood Fire",
    description: "Open-fire grill restaurant specialising in wood-fired meats and seafood. The smoke and char on everything is incredible. Rustic, carnivore-friendly, and seriously satisfying.",
    cuisine: "Grill / Wood-fire",
    category: "restaurant",
    price: "$$",
    rating: 4.5,
    area: "Central Ubud",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Batubara+Wood+Fire/data=!4m2!3m1!1s0x2dd23d75ac9a1075:0x535f5bcd39641dc2",
    emoji: "🔥",
    tags: ["Grill", "Smoky", "Carnivore"],
    lat: -8.523006,
    lng: 115.263376
  },
  {
    id: "ubd-013",
    name: "Cantina Rooftop Bali",
    description: "Rooftop bar and restaurant with views over the Ubud jungle canopy. Mexican-inspired food, cocktails, and a relaxed party vibe that's unusual for Ubud.",
    cuisine: "Mexican / Bar",
    category: "bar",
    price: "$$",
    rating: 4.2,
    area: "Central Ubud",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Cantina+Rooftop+Bali/data=!4m2!3m1!1s0x2dd23d38e5105043:0xd70db56e528950d9",
    emoji: "🌮",
    tags: ["Rooftop", "Views", "Party"],
    lat: -8.504764,
    lng: 115.254103,
    instagram: "boomboomubud"
  },
  {
    id: "ubd-014",
    name: "The Sayan House Restaurant",
    description: "Perched above the Ayung River valley in Sayan with breathtaking jungle views. Mediterranean and Indonesian fusion cuisine in one of Ubud's most beautiful settings. Worth it for the view alone.",
    cuisine: "Mediterranean / Indonesian",
    category: "restaurant",
    price: "$$$",
    rating: 4.4,
    area: "Sayan",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/The+Sayan+House+Restaurant/data=!4m2!3m1!1s0x2dd23d25ad4177df:0xf79f0f383121f82d",
    emoji: "🌴",
    tags: ["Views", "Romantic", "Splurge"],
    lat: -8.498808,
    lng: 115.244017
  },
  {
    id: "ubd-015",
    name: "Pica South American Kitchen",
    description: "South American restaurant bringing ceviches, empanadas, and grilled meats to Ubud. Bold flavours, good cocktails, and a colourful, energetic atmosphere.",
    cuisine: "South American",
    category: "restaurant",
    price: "$$",
    rating: 4.4,
    area: "Central Ubud",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Pica+South+American+Kitchen/data=!4m2!3m1!1s0x2dd23d6b823e538d:0x1f6df137fa764067",
    emoji: "🇵🇪",
    tags: ["Latin", "Ceviche", "Lively"],
    lat: -8.510045,
    lng: 115.263235
  },
  {
    id: "ubd-016",
    name: "Mozaic",
    description: "Award-winning fine dining restaurant and Ubud institution. French technique meets Indonesian seasonal ingredients in a 6 or 8-course tasting menu. Named joint #1 fine dining in Indonesia for 2025. The open-air garden setting under the stars is impossibly romantic.",
    cuisine: "French-Indonesian / Fine dining",
    category: "restaurant",
    price: "$$$",
    rating: 4.5,
    area: "Kedewatan",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Mozaic/data=!4m2!3m1!1s0x2dd23d30b9e78c4d:0x4332678847f3b761",
    emoji: "⭐",
    tags: ["Fine dining", "Must-do", "Romantic"],
    lat: -8.494850,
    lng: 115.253294,
    instagram: "mozaicrestaurantubud"
  },
  {
    id: "ubd-017",
    name: "Apéritif Restaurant",
    description: "Grand colonial-style fine dining restaurant at the Viceroy Bali resort. European cuisine with Asian accents, impeccable service, and a jaw-dropping valley setting. One of Bali's most elegant dining rooms.",
    cuisine: "European / Fine dining",
    category: "restaurant",
    price: "$$$",
    rating: 4.6,
    area: "Kedewatan",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Ap%C3%A9ritif+Restaurant/data=!4m2!3m1!1s0x2dd23d92488c4abd:0x91c1eb7c5e932bb0",
    emoji: "🥂",
    tags: ["Fine dining", "Elegant", "Special occasion"],
    lat: -8.493686,
    lng: 115.277516,
    instagram: "aperitifbali"
  },
  {
    id: "ubd-018",
    name: "Kebun Bistro",
    description: "Relaxed garden bistro on Ubud's main street serving Indonesian and international comfort food. Good value, generous portions, and a lovely shaded outdoor terrace.",
    cuisine: "Indonesian / International",
    category: "restaurant",
    price: "$",
    rating: 4.4,
    area: "Central Ubud",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Kebun+Bistro/data=!4m2!3m1!1s0x2dd23d6db2ede0a5:0x3d500c15e592b65f",
    emoji: "🌿",
    tags: ["Garden", "Value", "Casual"],
    lat: -8.513760,
    lng: 115.264182
  },

  // ═══════════════════════════════════════
  //  PAMELA'S BALI LIST (additional unique venues)
  // ═══════════════════════════════════════

  {
    id: "pam-001",
    name: "Bingin Beach",
    description: "One of Bali's most beautiful beaches, accessed by a steep staircase down the cliff. White sand, turquoise water, and a string of laid-back beach bars. Best at low tide when the sand opens up.",
    cuisine: "Beach",
    category: "activity",
    price: "$",
    rating: 4.7,
    area: "Bingin",
    region: "uluwatu",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Bingin+Beach/data=!4m2!3m1!1s0x2dd24546940a36b9:0xdca26390e6f01d95",
    emoji: "🏖️",
    tags: ["Beach", "Beautiful", "Must-do"],
    lat: -8.805692,
    lng: 115.113038
  },
  {
    id: "pam-002",
    name: "Amed",
    description: "Quiet fishing village on Bali's east coast known for incredible snorkelling and diving. The Japanese shipwreck dive site is famous. A completely different pace from the south — raw, peaceful, authentic.",
    cuisine: "Destination",
    category: "activity",
    price: "$",
    rating: 4.6,
    area: "East Bali",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Amed/data=!4m2!3m1!1s0x2dd20062e4022fc5:0x2dc34e6b4e3b97bf",
    emoji: "🤿",
    tags: ["Diving", "Quiet", "Off-trail"],
    lat: -8.350829,
    lng: 115.682332
  },
  {
    id: "pam-003",
    name: "Penida Island",
    description: "Rugged island off Bali's southeast coast with dramatic cliff formations, manta ray snorkelling, and the famous Kelingking Beach viewpoint. A full day trip from the mainland — bumpy roads but worth it.",
    cuisine: "Island / Day trip",
    category: "activity",
    price: "$",
    rating: 4.5,
    area: "Nusa Penida",
    region: "ubud",
    userNote: null,
    mapsUrl: "https://www.google.com/maps/place/Penida+Island/data=!4m2!3m1!1s0x2dd271194d1319d3:0x5c3a3706b2197b7b",
    emoji: "🏝️",
    tags: ["Day trip", "Scenic", "Must-do"],
    lat: -8.727807,
    lng: 115.544423
  }
];
